BlogApp.WebUI/Models/BlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class BlogModel
    {
    }
}

BlogApp.WebUI/Models/HomeBlogModel.cs
using BlogApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class HomeBlogModel
    {
        public List<Blog> SliderBlogs { get; set; }
        public List<Blog> HomeBlogs { get; set; }
    }
}

BlogApp.WebUI/Components/CategoryMenuViewComponent.cs
using BlogApp.Data.Abstracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryRepository _categoryRepository;
        public CategoryMenuViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public IViewComponentResult Invoke(ICategoryRepository categoryRepository)
        {
            return View(_categoryRepository.GetAll());
        }
    }
}

BlogApp.WebUI/Controllers/BlogController.cs
using BlogApp.Data.Abstracts;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        private ICategoryRepository _categoryRepository;
        public BlogController(IBlogRepository blogRepository, ICategoryRepository categoryRepository)
        {
            _blogRepository = blogRepository;
            _categoryRepository = categoryRepository;
        }

        [HttpGet]
        public IActionResult Index(int? id, string q)
        {
            var query = _blogRepository.GetAll().Where(x => x.IsApproved);

            if (id != null)
            {
                query = query.Where(x => x.CategoryId == id);
            }

            if (!string.IsNullOrWhiteSpace(q))
            {
                query = query.Where(x => EF.Functions.Like(x.Title, "%" + q + "%")
                || EF.Functions.Like(x.Description, "%" + q + "%")
                || EF.Functions.Like(x.Body, "%" + q + "%"));
            }

            ViewBag.SelectedCategoryId = RouteData?.Values["Id"];
            return View(query.OrderByDescending(x => x.Date));
        }

        // Edit Actions
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");

            return View(_blogRepository.GetById((int)id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog blog, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot\\img\\{file.FileName}");

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    blog.ImagePath = file.FileName;
                }
                _blogRepository.SaveBlog(blog);
                TempData["message"] = $"{blog.Title} kayıt edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View(blog);
        }

        //Create Actions
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");

            return View();
        }
        [HttpPost]
        public IActionResult Create(Blog blog)
        {
            if (ModelState.IsValid)
            {
                _blogRepository.SaveBlog(blog);
                TempData["message"] = $"{blog.Title} kayıt edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View(blog);
        }


        //Delete Actions
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_blogRepository.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _blogRepository.DeleteBlog(id);
            TempData["message"] = $"{id} numarali kayit silindi.";
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            return View(_blogRepository.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(_blogRepository.GetById(id));
        }
    }
}

BlogApp.WebUI/Controllers/CategoryController.cs
using BlogApp.Data.Abstracts;
using BlogApp.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository _repo;
        public CategoryController(ICategoryRepository repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            return View(_repo.GetAll());
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_repo.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _repo.DeleteCategory(id);
            TempData["message"] = $"{id} numarali kayit silindi.";
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult AddOrUpdate(int? id)
        {
            ViewBag.Categories = new SelectList(_repo.GetAll(), "Id", "Name");

            if (id == null)
            {
                return View(new Category());
            }

            return View(_repo.GetById((int)id));
        }
        [HttpPost]
        public IActionResult AddOrUpdate(Category category)
        {
            if (ModelState.IsValid)
            {
                _repo.SaveCategory(category);
                TempData["message"] = $"{category.Name} kayit edildi.";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_repo.GetAll(), "Id", "Name");
            return View(category);
        }
    }
}

BlogApp.WebUI/Controllers/HomeController.cs
using BlogApp.Data.Abstracts;
using BlogApp.Data.Concrete.EfCore;
using BlogApp.Entity;
using BlogApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository _repo;

        public HomeController(IBlogRepository repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            HomeBlogModel homeBlogModel = new HomeBlogModel();
            homeBlogModel.HomeBlogs = new List<Blog>(_repo.GetAll().Where(x => x.IsApproved && x.IsHome).ToList());
            homeBlogModel.SliderBlogs = new List<Blog>(_repo.GetAll().Where(x => x.IsApproved && x.IsSlider).ToList());

            return View(homeBlogModel);
        }

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }
    }
}

BlogApp.WebUI/Views/Blog/AddOrUpdate.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit";
    Layout = "_AdminLayout";
}

<div class="container mt-3">
    <h1>Edit Blog</h1>

    <form method="post">
        <input type="hidden" asp-for="Id" class="form-control" />
        <div class="form-group">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label for="ImagePath">ImagePath</label>
            <input asp-for="ImagePath" class="form-control" />
        </div>

        <div class="form-group">
            <label for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsApproved" class="form-check-input">
                Is Approved
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsHome" class="form-check-input">
                Is Home
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsSlider" class="form-check-input">
                Is Slider
            </label>
        </div>

        <div class="form-group">
            <label for="CategoryId">Category</label>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                <option selected disabled>Select category</option>
            </select>
        </div>

        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h1>Create Blog</h1>

    <form method="post">
        <input type="hidden" asp-for="Id" class="form-control" />
        <div class="form-group">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label for="CategoryId">Category</label>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                <option selected disabled>Select category</option>
            </select>
        </div>

        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>

BlogApp.WebUI/Views/Blog/Delete.cshtml
@model Blog
@{
    ViewData["Title"] = "Delete";
    Layout = "_AdminLayout";
}

<form method="post">
    <h1>@Model.Title silinsin mi? </h1>
    <button class="btn btn-primary">Delete</button>
</form>

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">

            <div class="card mb-2">
                <div class="card-header">
                    @Model.Title
                </div>
                <img class="card-img-top" src="~/img/@Model.ImagePath" alt="@Model.Title">
                <div class="card-block">
                    <h4 class="card-title">@Model.Title</h4>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Model.Date</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>

        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section scripts
{
    <script src="/node_modules/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Body")
    </script>
}

<div class="container mt-3">
    <h1>Edit Blog</h1>

    <form method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="Id" class="form-control" />
        <input type="hidden" asp-for="ImagePath" class="form-control" />

        <div class="form-group">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <img src="~/img/@Model.ImagePath" width="120" />
            <input type="file" id="file" name="file" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsApproved" class="form-check-input">
                Is Approved
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsHome" class="form-check-input">
                Is Home
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsSlider" class="form-check-input">
                Is Slider
            </label>
        </div>

        <div class="form-group">
            <label for="CategoryId">Category</label>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                <option selected disabled>Select category</option>
            </select>
        </div>

        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_blogList", Model)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IQueryable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "_AdminLayout";
}


<div class="container mt-3">
    <h1>Blog List</h1>
    <hr />
    <a class="btn btn-primary"
       href="/blog/create">Create</a>
    <hr />
    <div class="row">
        <div class="col">

            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Date</th>
                        <th>is Approved</th>
                        <th>is Home</th>
                        <th>is Slider</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var blog in Model)
                    {
                        <tr>
                            <td>@blog.Id</td>
                            <td>
                                <img src="~/img/@blog.ImagePath" width="100" />
                            </td>
                            <td>@blog.Title</td>
                            <td>@blog.Date</td>

                            <td>
                                @if (blog.IsApproved)
                                {
                                    <i class="fas fa-check"></i>

                                }
                                else
                                {
                                    <i class="fas fa-times"></i>
                                }
                            </td>

                            <td>
                                @if (blog.IsHome)
                                {
                                    <i class="fas fa-check"></i>

                                }
                                else
                                {
                                    <i class="fas fa-times"></i>
                                }
                            </td>

                            <td>
                                @if (blog.IsSlider)
                                {
                                    <i class="fas fa-check"></i>

                                }
                                else
                                {
                                    <i class="fas fa-times"></i>
                                }
                            </td>

                            <td>
                                <a class="btn btn-sm btn-success" asp-controller="Blog" asp-action="Edit"
                                   asp-route-id="@blog.Id">Details</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Blog" asp-action="Delete"
                                   asp-route-id="@blog.Id">Remove</a>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

BlogApp.WebUI/Views/Category/AddOrUpdate.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
    Layout = "_AdminLayout";
}

<div class="container mt-3">
    <h1>Create</h1>
    <br/>

    <form method="post">
        <input type="hidden" class="form-control" asp-for="Id"/>
        <div class="form-group">
            <label for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>

        <input class="btn btn-primary" type="submit" value="Submit" />

    </form>
</div>

BlogApp.WebUI/Views/Category/Delete.cshtml
@model Category
@{
    ViewData["Title"] = "Delete";
    Layout = "_AdminLayout";
}

<form method="post">
    <h1>@Model.Name silinsin mi? </h1>
    <button class="btn btn-primary">Delete</button>
</form>

BlogApp.WebUI/Views/Category/List.cshtml
@model IQueryable<Category>
@{
    ViewData["Title"] = "List";
    Layout = "_AdminLayout";
}

    <div class="container mt-3">
        <h1>Category List</h1>
        <br />
        <div class="row">
            <div class="col">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var category in Model)
                        {
                            <tr>
                                <td>@category.Id</td>


                                <td>@category.Name</td>

                                <td>
                                    <a class="btn btn-sm btn-success" asp-controller="Category" asp-action="AddOrUpdate"
                                       asp-route-id="@category.Id">Details</a>
                                </td>

                                <td>
                                    <a class="btn btn-sm btn-danger" asp-controller="Category" asp-action="Delete"
                                       asp-route-id="@category.Id">Remove</a>
                                </td>

                            </tr>
                         }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

BlogApp.WebUI/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
                <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/1.jpg" alt="Card image cap">
                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>

BlogApp.WebUI/Views/Home/Index.cshtml
@model HomeBlogModel
@{
    ViewData["Title"] = "Blog App";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_slider", Model.SliderBlogs)
            @Html.Partial("_blogList", Model.HomeBlogs)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/List.cshtml
@{
    ViewData["Title"] = "List";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
             <div class="list-group">
                 <a href="#" class="list-group-item active">
                     Cras justo odio
                 </a>
                 <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
                 <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
                 <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
                 <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
             </div>
         </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/1.jpg" alt="Card image cap">
                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>   

BlogApp.WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">
    @foreach (var item in Model)
    {
        <a asp-controller="Blog"
           asp-action="Index"
           asp-route-id="@item.Id"
           class="list-group-item @(ViewBag.SelectedCategoryId == item.Id.ToString() ? "active" : "")">
            @item.Name
        </a>
    }
</div>

BlogApp.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
    <link href="~/css/bundle.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Admin</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/home">Go user page <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/list">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/category/list">Category</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div id="main">
        <div class="container">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">
                    @TempData["message"]
                </div>
            }
        </div>

        @RenderBody()
    </div>
    <script src="~/js/bundle.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

BlogApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Blog App</title>
    <link href="~/css/bundle.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">Blog App</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/list">go admin page</a>
                    </li>
                </ul>
                @Html.Partial("_searchBox")
            </div>
        </div>
    </nav>

    <div id="main">
        <div class="col md-9">
            <div class="container">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">
                        @TempData["message"]
                    </div>
                }

                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/js/bundle.js"></script>
</body>
</html>

BlogApp.WebUI/Views/Shared/_blogList.cshtml
@model IEnumerable<Blog>

    @if (Model.Count() != 0)
    {

        @foreach (var blog in Model)
        {
            <div class="card mb-2">
                <div class="card-header">
                    @blog.Title
                </div>
                <img class="card-img-top" src="~/img/@blog.ImagePath" alt="Card image cap">
                <div class="card-block">
                    <h4 class="card-title">@blog.Title</h4>
                    <p class="card-text">@blog.Description</p>
                    <a asp-controller="Blog" asp-action="Details"
                       asp-route-id="@blog.Id" class="btn btn-primary">Show details</a>
                </div>
            </div>
        }
    }
    else
    {
        <div class="alert alert-warning">Kayıt yok</div>
    }

BlogApp.WebUI/Views/Shared/_searchBox.cshtml
<form class="form-inline my-2 my-lg-0">
    <input id="q" name="q" class="form-control mr-sm-2" type="text" placeholder="Search">
    <button asp-controller="Blog" asp-action="Index" formmethod="get"
            class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

BlogApp.WebUI/Views/Shared/_slider.cshtml
@model IEnumerable<Blog>

<div id="carouselExampleIndicators" class="carousel slide mb-3" data-ride="carousel">
    <ol class="carousel-indicators">

        @for (int i = 0; i < Model.Count(); i++)
        {
            @if (i == 0)
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="active"></li>
            }
            else
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i"></li>
            }
        }
    </ol>
    <div class="carousel-inner" role="listbox">

        @{bool IsfirstSlide = false; }
        @foreach (var item in Model)
        {
            @if (!IsfirstSlide)
            {
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="~/img/@item.ImagePath" alt="@item.Title">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>@item.Title</h3>
                        <p>@item.Description</p>
                    </div>
                </div>
                IsfirstSlide = true;
            }
            else
            {
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="~/img/@item.ImagePath" alt="@item.Title">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>@item.Title</h3>
                        <p>@item.Description</p>
                    </div>
                </div>
            }
           
        }

    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>